[project]
name = "openlipsync"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests",
    "tqdm",
    "torch",
    "torchaudio",
    "numpy",
    "scikit-learn",
    "tensorboard",
    "matplotlib",
    "torchcodec>=0.6.0",
]
